config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_night, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @query = params[:query]
      @flats = Flat.where("name iLike '%#{params[:query]}%'")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit <%= @flat.name %></h1>
        <div class="mt-3">
          <%= form_for(@flat) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :number_of_guests %>
            <%= f.number_field :number_of_guests, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :price_per_night %>
            <%= f.number_field :price_per_night, class: 'form-control' %>
          </div>
          <div class="mt-3">
            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-12">
      <h1>All our Flats</h1>
    </div>
  </div>


    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4">
          <div class="flat-card bg-light">
            <!--<img src="..." class="card-img-top" alt="image"> -->
            <h3 class="card-title"> <%= flat.name %></h3>
            <h4 class=""> <%= flat.address  %></h4>
            <div class="flex">
              <i class="fas fa-user-friends"></i>
              <span> <%= flat.number_of_guests%> </span>
            </div>
            <div class="flex">
              <i class="fas fa-euro-sign"></i>
              <span> <%= flat.price_per_night %></span>
            </div>
            <div class="card-body bg-white border-top">
              <div class="flat-card-actions">
                <%= link_to 'More info', flat_path(flat) %>
                <%= link_to 'Edit', edit_flat_path(flat), class: 'ml-3 text-warning' %>
                <%= link_to "Remove", flat_path(flat),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'ml-3 text-danger'
            %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Add a new Flat</h1>
        <div class="mt-3">
          <%= form_for(@flat) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :address %>
            <%= f.text_field :address, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :number_of_guests %>
            <%= f.number_field :number_of_guests, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :price_per_night %>
            <%= f.number_field :price_per_night, class: 'form-control' %>
          </div>
          <div class="mt-3">
            <%= f.submit class: 'btn btn-primary' %>
            <%= link_to 'Cancel', '#', class: 'btn btn-danger ml-2' %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-8">
      <div class="flat-show-card">
        <h1><%= @flat.name %></h1>
        <p class="flat-show-address"><%= @flat.address %></p>
      </div>
      <div class="flat-show-card">
        <h3>A bit more about this flat...</h3>
        <p><%= @flat.description %></p>
      </div>
    </div>

    <div class="col-4">
      <div class="flat-show-card">
        <h5>Book this place!</h5>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <a href="/flats" class="navbar-brand">Simple Airbnb</a>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <a  href="#" class="btn btn-outline-success my-2 my-sm-0" role="button">Search</a>
        <a class="btn btn-outline-primary" href="/flats/new" role="button">Add Flat</a>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>